# Site settings
title: Patti Quattromani
email: patti@pattiquattromani.com
url: https://quattromani.github.io/
enforce_ssl: quattromani.github.io/pattiquattromani
description:
baseurl: "pattiquattromani"
twitter_username: frogprincess1974
github_username:  quattromani

google_analytics: true
google_analytics_id: UA-50387096-3

# Build settings
markdown: kramdown
permalink: pretty
