# Site settings
title: Patti Quattromani
email: patti@pattiquattromani.com
description: ""
url: https://quattromani.github.io/
enforce_ssl: quattromani.github.io/pattiquattromani/
description: A simple mileage tracker for leased vehicles
baseurl: "pattiquattromani"
baseurl: ""
url: "pattiquattromani"
twitter_username: frogprincess1974
github_username:  quattromani

google_analytics: true
google_analytics_id: UA-50387096-3

# Build settings
markdown: kramdown
permalink: pretty
